Terraform docs

diff --git a/bin/tf-helper b/bin/tf-helper
--- a/bin/tf-helper
+++ b/bin/tf-helper
@@ -34,6 +34,7 @@ tf_helper_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
+  printf "  %s   Refresh all terraform docs\n" "docs         "
   printf "  %s   Clean up tfplan files in all root modules\n" "clean        "
   printf "  %s   Run terraform init in a root module\n" "init         "
   printf "  %s   Run terraform plan in a root module\n" "plan         "
@@ -52,6 +53,40 @@ tf_helper_usage() {
     echo
     printf "  %s\n" "--version, -v"
     printf "    Show version number\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+tf_helper_docs_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "tf-helper docs - Refresh all terraform docs\n"
+    echo
+
+  else
+    printf "tf-helper docs - Refresh all terraform docs\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  tf-helper docs\n"
+  printf "  tf-helper docs --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  tf-helper docs\n"
     echo
 
   fi
@@ -429,6 +464,16 @@ inspect_args() {
 
 # :command.command_functions
 # :command.function
+tf_helper_docs_command() {
+  # src/docs_command.sh
+  parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
+  dest=$(dirname ${parent_path})/terraform
+
+  find ${dest} -type f -name 'main.tf' -not -path '*/.*' -execdir bash -c "terraform-docs markdown ./ > README.md" \;
+
+}
+
+# :command.function
 tf_helper_clean_command() {
   # src/clean_command.sh
   parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
@@ -541,6 +586,13 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    docs)
+      action="docs"
+      shift
+      tf_helper_docs_parse_requirements "$@"
+      shift $#
+      ;;
+
     clean)
       action="clean"
       shift
@@ -595,6 +647,52 @@ parse_requirements() {
       ;;
 
   esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+tf_helper_docs_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        tf_helper_docs_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+
+  # :command.command_filter
+  action="docs"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -1130,6 +1228,15 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "docs")
+      if [[ ${args['--help']:-} ]]; then
+        long_usage=yes
+        tf_helper_docs_usage
+      else
+        tf_helper_docs_command
+      fi
+      ;;
+
     "clean")
       if [[ ${args['--help']:-} ]]; then
         long_usage=yes
